### PR TITLE
Multi text loop

### PR DESCRIPTION
**Pull request by alcidesbsilvaneto**
As this was the only library that actually worked for me, and the only function missing was the loop, I decided to add it to the code. Hope everything is ok.

### CODE REVIEW

**Review by devmuhammad — APPROVED** [review]

**Comment by dannyjmac** [comment]
LGTM

**Comment by dannyjmac** [comment]
Maybe you can update the readme too with `multiTextLoop` prop

**Comment by alcidesbsilvaneto** [comment]
Yes, of course. Could you show me the process? I never did a contribution before. 
Should I make a new commit? Can I edit this one?

**Comment by kevoese** [comment]
Merged and published @alcidesbsilvaneto . Thanks for the help.

**Comment by tariqhirji** [comment]
A loop property is exactly what this package needs. Very good package but missing that key piece. I see that @alcidesbsilvaneto made a PR for it last summer and it is indeed added by @kevoese . Would it be possible to add this into the readme or the example usages? Perhaps even in the 'Properties and description' as I am unsure of how to utilize this loop functionality that was added. Not sure if it is shown anywhere or I just missed it.

**Pull request merged**
